# Generated by Django 5.1.5 on 2025-01-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=15, verbose_name="Название")),
            ],
            options={
                "verbose_name": "День недели",
                "verbose_name_plural": "Дни недели",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.TimeField(verbose_name="Время, когда привычка будет выполняться")),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                ("is_pleasant_habit", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                ("reward", models.CharField(blank=True, max_length=150, null=True, verbose_name="Вознаграждение")),
                ("lead_time", models.PositiveSmallIntegerField(default=60, verbose_name="Время на выполнение")),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная привычка")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="habits",
                        to="habits.place",
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "frequency",
                    models.ManyToManyField(
                        default=[1, 2, 3, 4, 5, 6, 7], to="habits.weekday", verbose_name="Периодичность"
                    ),
                ),
            ],
        ),
    ]
