# Generated by Django 5.1.5 on 2025-01-31 06:22

import django.contrib.postgres.fields
import django.core.validators
import src.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                default=src.utils.week_days,
                size=None,
                validators=[
                    django.core.validators.MinLengthValidator(1, "Привычка должна выполняться минимум 1 раз в неделю")
                ],
                verbose_name="Периодичность",
            ),
        ),
    ]
